<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.temporal.docs</groupId>
  <artifactId>external-storage</artifactId>
  <version>1.0.0</version>

  <properties>
    <maven.compiler.release>10</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.temporal</groupId>
      <artifactId>temporal-sdk</artifactId>
      <version>1.39.0</version>
    </dependency>
    <dependency>
      <groupId>io.temporal</groupId>
      <artifactId>temporal-payload-storage-s3driver</artifactId>
      <version>1.39.0</version>
    </dependency>
    <dependency>
      <groupId>io.temporal</groupId>
      <artifactId>temporal-payload-storage-s3driver-awssdkv2</artifactId>
      <version>1.39.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
      </plugin>
    </plugins>
  </build>
</project>
