[package]
name = "temporal-hello-world"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
serde = { version = "1", features = ["derive"] }
temporalio-client = "1.0.0"
temporalio-common = "1.0.0"
temporalio-macros = "1.0.0"
temporalio-sdk = "1.0.0"
temporalio-workflow = "1.0.0"
tokio = { version = "1", features = ["full"] }
